export const ADD_INGREDIENTS = "ADD_INGREDIENT";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS ="SET_INGREDIENTS"
export const FETCH_INGREDIENTS_FAILD = "FETCH_INGREDIENTS_FAILD"
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS"
export const PURCHASE_BURGER_FAIL ="PURCHASE_BURGER_FAIL"
export const PURCHASE_BURGER_START = " "
export const PURCHASE_INIT = "PURCHASE_INIT"




